### PR TITLE
[Slot] Fix children expectation when using `Slottable`

### LINKED ISSUE #1261: [Slot] `Slottable` not working as expected
See https://github.com/radix-ui/primitives/discussions/1255

### PR DESCRIPTION
**Pull request by benoitgrelard**
Fixes #1261

### CODE REVIEW

**Comment by benoitgrelard** [comment]
Looks like that broke a few chromatic tests, looking into it.

File: packages/react/slot/src/Slot.tsx [hunk 1]
```diff
@@ -11,20 +11,29 @@ interface SlotProps extends React.HTMLAttributes<HTMLElement> {
...
+
+  if (slottable) {
+    const newElement = slottable.props.children;
+    const newChildren = childrenArray.map((child) => {
+      if (child === slottable) {
+        const slottableChildren = slottable.props.children as React.ReactNode;
+        if (React.Children.count(slottableChildren) > 1) return React.Children.only(null);
+        return React.isValidElement(slottableChildren)
+          ? (slottableChildren.props.children as React.ReactNode)
+          : null;
```
Comment (andy-hook) [inline packages/react/slot/src/Slot.tsx:25]: Is it worth us providing some comments to explain the flow here? the children of children is a bit of a mind bender without context. Hard to know if I'm finding it easier to follow simply because I already have that context.

Comment (benoitgrelard) [reply packages/react/slot/src/Slot.tsx]: I've added comment but also re-wrote it a bit which I think makes it easier to read.
Let me know your thoughts: https://github.com/radix-ui/primitives/pull/1376/commits/cb531c0c3faf85ae0e6efa4d872fcc4d9f88475d

File: packages/react/slot/src/Slot.stories.tsx [hunk 2]
```diff
@@ -53,6 +53,31 @@ export const WithComposedEvents = () => (
   </>
 );
 
+export const ButtonAsLink = () => (
+  <>
+    <h1>Button with left/right icons</h1>
+    <Button
+      iconLeft={<FakeIcon color="tomato" />}
+      iconRight={<FakeIcon color="royalblue" />}
+      ref={console.log}
```
[the remark this answers is not in the document]
Comment (andy-hook) [reply packages/react/slot/src/Slot.stories.tsx:62]: Ah, makes sense 👍

**Review by andy-hook — APPROVED** [review]
