### PR TITLE
[Select] Fix compatibility with React > 16.8

### LINKED ISSUE #1205: react-select not working as expectedly with react 16.14
### Current Behavior
When using @radix-ui/react-select with react 16.14.0 two issues are happening as following:
1. using cursor, click on button trigger. select options list appear for **split second** and closes [double click happening]
2. open select menu using keyboard, now try to select any option **with cursor**. user needs to double click to select the option.

### Expected behavior
Either it should work as it's working with react 17+
or documentation should mention the minimum version limitation (if not going to support 16.8+)

### Reproducible example

[CodeSandbox reproduction](https://codesandbox.io/s/react-select-on-react-16-19bb56?file=/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-select       |      0.1.0   |
| React            | n/a     | 16.14.0        |
| Browser          |   chrome      |  98       |
| Assistive tech   |    n/a     |   n/a      |
| Node             | n/a     |    n/a     |
| npm/yarn         |     n/a    |    n/a     |
| Operating System |    mac OS Monterey    |   12.2.1      |

### PR DESCRIPTION
**Pull request by benoitgrelard**
Fixes #1205

### CODE REVIEW

File: packages/react/select/src/Select.tsx [hunk 1]
```diff
@@ -105,6 +106,7 @@ const Select: React.FC<SelectProps> = (props: ScopedProps<SelectProps>) => {
   // We set this to true by default so that events bubble to forms without JS (SSR)
   const isFormControl = trigger ? Boolean(trigger.closest('form')) : true;
   const [bubbleSelect, setBubbleSelect] = React.useState<HTMLSelectElement | null>(null);
+  const triggerPointerDownRef = React.useRef<{ x: number; y: number } | null>(null);
```
Comment (benoitgrelard) [inline packages/react/select/src/Select.tsx:109]: Should I rename this `triggerPointerDownPosRef`?

Comment (benoitgrelard) [reply packages/react/select/src/Select.tsx:109]: Renamed as I think it makes more sense.

Comment (andy-hook) [reply packages/react/select/src/Select.tsx]: Yeah, totally

**Review by jjenzz — APPROVED** [review]
