### PR TITLE
[ScrollArea] Fix `forceMount` type on `Scrollbar`

### LINKED ISSUE #728: [ScrollArea] ScrollArea.Scrollbar loses types after being put through a Stitches styled call
### Current Behavior
When styling the Scrollbar of ScrollArea like this:
```
const StyledScrollbar = styled(ScrollArea.Scrollbar, {
...
});
```

Where styled is a stitches styled, and if `forceMount` is passed on or any of the primitive props to it, there are Typescript errors:

image

### Expected behaviour

Types are preserved even after putting the component through a JSS styling function.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/jovial-payne-j2dqg?file=/src/App.tsx)

### Additional context

The bug occurs after wrapping a Radix component in a Stitches `styled` function. None of the props exposed and documented in the docs are then recognized by typescript.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    ScrollArea     |     0.0.14    |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |    92.0.4515.51     |
| Assistive tech   |         |         |
| Node             | n/a     |     15    |
| npm/yarn         |    yarn     |    1.22.5     |
| Operating System |    MacOS     |    Big Sur 11.3.1     |

### PR DESCRIPTION
**Pull request by jjenzz**
Fixes #728 

The bug was caused because of the `ScrollAreaScrollbarVisible` part of the union which doesn't have a `forceMount` prop. It looks like this was confusing the type implementation for Stitches and styled-components.

It works fine without these libraries e.g. `React.ComponentProps<typeof ScrollArea.Scrollbar>` reports fine but I've made this change anyway to please external libs. Not sure why they break.

### CODE REVIEW

File: packages/react/scroll-area/src/ScrollArea.tsx [hunk 1]
```diff
@@ -196,17 +196,12 @@ ScrollAreaViewport.displayName = VIEWPORT_NAME;
...
 const SCROLLBAR_NAME = 'ScrollAreaScrollbar';
 
-type ScrollAreaScrollbarOwnProps =
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarAuto>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarHover>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarScroll>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarVisible>;
-
+type ScrollAreaScrollbarOwnProps = Polymorphic.Merge<
+  Polymorphic.OwnProps<typeof ScrollAreaScrollbarVisible>,
```
Comment (jjenzz) [inline packages/react/scroll-area/src/ScrollArea.tsx:200]: They all eventually render a `ScrollAreaScrollbarVisible`. Not ideal that we have to type this assumption here but not sure what else we can do.

File: packages/react/scroll-area/src/ScrollArea.tsx [hunk 2]
```diff
@@ -196,17 +196,12 @@ ScrollAreaViewport.displayName = VIEWPORT_NAME;
 
 const SCROLLBAR_NAME = 'ScrollAreaScrollbar';
 
-type ScrollAreaScrollbarOwnProps =
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarAuto>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarHover>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarScroll>
-  | Polymorphic.OwnProps<typeof ScrollAreaScrollbarVisible>;
-
+type ScrollAreaScrollbarOwnProps = Polymorphic.Merge<
```
Comment (benoitgrelard) [inline packages/react/scroll-area/src/ScrollArea.tsx:199]: ok so we end up with simplified types whilst slightly inaccurate in the sense that if you use the visible one, TS will let you add a `forceMount` prop without complaints even though it doesn't apply?

File: packages/react/scroll-area/src/ScrollArea.tsx (hunk 1 above)
Comment (benoitgrelard) [reply packages/react/scroll-area/src/ScrollArea.tsx:200]: ok so we end up with simplified types whilst slightly inaccurate in the sense that if you use the visible one, TS will let you add a forceMount prop without complaints even though it doesn't apply?

Comment (jjenzz) [reply packages/react/scroll-area/src/ScrollArea.tsx:200]: If you use `type="always"` it will say it accepts a `forceMount` prop which is kinda irrelevant there because `type="always"` is always mounted by nature of the type haha. 

So yeah, it will accept the `forceMount` prop but do nothing with it.

**Review by benoitgrelard — APPROVED** [review]
