### PR TITLE
[Presence] Allow close animation only

### LINKED ISSUE #635: [Presence] Animation fails to run in certain conditions
### Current Behavior

When providing a single exit animation, `Presence` will only animate into the unmounted state once.

### Expected behavior

It should always perform the animation when transitioning to an unmounted state.

### Reproducible example

https://codesandbox.io/s/inspiring-dirac-zheqh

Hide content -> animation works -> show content -> hide content -> no animation

### PR DESCRIPTION
**Pull request by jjenzz**
I'm still struggling with some `Toast` animation bits which I'll continue to try solve separately but this at least fixes #635 for the timebeing.

### CODE REVIEW

File: packages/react/presence/src/Presence.tsx [hunk 1]
```diff
@@ -47,6 +47,11 @@ function usePresence(present: boolean) {
     },
   });
 
+  React.useEffect(() => {
+    const currentAnimationName = getAnimationName(stylesRef.current);
+    prevAnimationNameRef.current = state === 'mounted' ? currentAnimationName : 'none';
```
Comment (jjenzz) [inline packages/react/presence/src/Presence.tsx:52]: The cause of the original issue was that when animating out the first time the `prevAnimationNameRef.current` was becoming `hGfvx` or something (the name of the close animation) and then when remounting there was no animation so `prevAnimationNameRef.current` was still set to the close animation.

That meant that the second time it tried to close, the previous and current animation values would be the same and it wouldn't suspend unmount as it though there wasn't an animation initiating.

This change ensures that when the component unmounts we always set the previous animation to `none`.

File: packages/react/presence/src/Presence.tsx [hunk 2]
```diff
@@ -96,33 +101,20 @@ function usePresence(present: boolean) {
...
       };
-
-      const handleAnimationStart = (event: AnimationEvent) => {
-        if (event.target === node) {
-          // if animation occurred, store its name as the previous animation.
-          prevAnimationNameRef.current = getAnimationName(stylesRef.current);
-        }
-      };
-
-      node.addEventListener('animationstart', handleAnimationStart);
```
Comment (jjenzz) [inline packages/react/presence/src/Presence.tsx:107]: I remembered that we added all this stuff before for a reason so I went through GitHub history and validated the issues that this originally solved are still working here.

**Review by benoitgrelard — APPROVED** [review]

**Review by andy-hook — APPROVED** [review]
