### PR TITLE
[ScrollArea] Viewport fixes

### LINKED ISSUE #926: [ScrollArea] Content with ellipsis CSS bursts out of container.
Issue: https://codesandbox.io/s/frosty-cerf-poy3y?file=/src/styles.css
Example of native scrollable without this issue: https://codepen.io/jjenzz/pen/jOLMjvJ

I'm wondering if we still need the `display: table` stuff now so will investigate getting rid of that as a potential solution at some stage.

### PR DESCRIPTION
**Pull request by vladmoroz**
- Fix `asChild` prop not working as expected on the Viewport part
- Rework the inner content element styles on the Viewport part
  - Replace `display: table` with flex styles on the parent that allow the viewport to fill container height (based on the [Radix Themes implementation](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/scroll-area.css#L40))
  - Replace most related inline styles with 0,0,0 specificity styles for easier overrides via `[data-radix-scroll-area-content]`
  - Fix `text-overflow: ellipsis` not working when used with a vertical scrollbar

Closes #926 #1666

### CODE REVIEW

File: packages/react/scroll-area/src/ScrollArea.tsx [hunk 1]
```diff
@@ -1010,6 +1035,26 @@ function useResizeObserver(element: HTMLElement | null, onResize: () => void) {
...
+) {
+  const { asChild, children } = options;
+  if (!asChild) return typeof content === 'function' ? content(children) : content;
+
+  const firstChild = React.Children.only(children) as React.ReactElement;
+  return React.cloneElement(firstChild, {
+    children: typeof content === 'function' ? content(firstChild.props.children) : content,
+  });
+}
+
```
Comment (vladmoroz) [inline packages/react/scroll-area/src/ScrollArea.tsx:1057]: We worked this out in https://github.com/radix-ui/themes/pull/311

**Comment by mboudreau** [comment]
Any progress on this?  I just hit this issue today...

**Comment by fkysly** [comment]
Any progress on this too...

**Comment by Crisis2010** [comment]
Same here, have tmp fix, but need proper

**Review by chaance — APPROVED** [review]

**Comment by lazakrisz** [comment]
thank you so much folks 🙏

**Comment by kognise** [comment]
FYI this caused a breaking regression for us. `width: min-content` on the inner container caused horizontal layouts inside vertical scroll areas to not be full width. For now we are doing:

```css
.rt-ScrollAreaViewport>* {
  width: 100%;
}
```

but it doesn't seem very correct? Not entirely sure.

**Comment by TimChild** [comment]
I have the same issue as @kognise

**Comment by chaance** [comment]
Reverted in 1.2.1 to fix the regression. Will revisit this at a later date.

**Comment by Georgegriff** [comment]
That's unfortunate, the removal of display table in this pr fixed other things, such as being able to properly use flexbox to dynamically size the scroll height, was relying on it. hopefully there's a way of bringing it back

**Comment by chaance** [comment]
@Georgegriff I know. I'm planning to come back to this but I think the splash radius here for breaking apps is a little too big to justify in a patch release. We'll either re-release it in a major or adjust it to avoid breakage.

**Comment by Georgegriff** [comment]
Any luck on coming back to this at all? this component being flex box rather than table was so nice
