### PR TITLE
[Presence] Add support for multiple animations

### LINKED ISSUE #568: Popover does not close when an animation is present
## Bug report

The popover (v0.0.8) does not close when clicking away if the `Popover.Content` element has some css animation.

I've tested and it works fine in v0.0.7 and v0.0.6.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/exciting-lederberg-s0mfj?file=/src/App.js:0-415)

### Your environment

MacOS, latest Chrome

### PR DESCRIPTION
**Pull request by jjenzz**
### Description

Bit of an oversight here 🙈  

Took me a while to figure this all out but ended up being a few simple changes in the end.

Fixes #568.

### CODE REVIEW

File: packages/react/presence/src/Presence.tsx [hunk 1]
```diff
@@ -90,18 +90,25 @@ function usePresence(present: boolean) {
...
-          // if animation occurred, store its name as the previous animation
-          prevAnimationNameRef.current = getAnimationName(stylesRef.current);
           send('ANIMATION_END');
         }
       };
 
+      const handleAnimationStart = (event: AnimationEvent) => {
+        if (event.target === node) {
+          // if animation occurred, store its name as the previous animation.
+          prevAnimationNameRef.current = getAnimationName(stylesRef.current);
```
Comment (jjenzz) [inline packages/react/presence/src/Presence.tsx:102]: I had to move this to `animationstart` because if the animation in doesn't complete before the button is pressed again to close, the `animationend` wouldn't have fired so the `prevAnimationName` would be incorrect.

Comment (benoitgrelard) [reply packages/react/presence/src/Presence.tsx:102]: Just to confirm, this change is unrelated to having to support multiple animations right? Just an edge case you discovered whilst fixing this, in case you toggle the state quickly?

**Review by benoitgrelard — COMMENTED** [review]
Looks good, just one question.

File: packages/react/presence/src/Presence.tsx (hunk 1 above)
Comment (jjenzz) [reply packages/react/presence/src/Presence.tsx:102]: You got it :+1:

**Review by benoitgrelard — APPROVED** [review]
