### PR TITLE
[Tooltip] Fix trigger when another tooltip overlays it

### LINKED ISSUE #1001: [Tooltip] tooltip is not triggered when tooltip covers trigger
## Bug report

Tooltip is not triggered when tooltip covers trigger.

### Current Behavior

When you have a tooltip that covers a trigger, it is possible to end up hovering over a trigger and no tooltip displayed.

I tried using `pointerEvent: "none",` on the tooltip content, but that didn't seem to work.

### Expected behavior

When focusing on a trigger after a tooltip is hidden, it should show always show the tooltip.

### Reproducible example

https://codesandbox.io/s/dazzling-haze-4z9r5?file=/App.js

In the example sandbox:

1. Start with mouse off both buttons and no tooltip showing
1. Hover on button 1, wait untill tooltip is shown
1. Quickly move mouse onto button 2

The image below shows an icon hovered (red) and no tooltip.

image

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     radix-ui/react-tooltip    |   0.1.1      |
| React            | n/a     |     17.0.2    |
| Browser          |     Chrome    |      96.0.4664.45    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    Windows     |    10     |

### PR DESCRIPTION
**Pull request by jjenzz**
Fixes #1001 

I mentioned on that ticket that I would look into this as part of the tooltip work.

### CODE REVIEW

File: packages/react/tooltip/src/Tooltip.tsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ const TooltipTrigger = React.forwardRef<TooltipTriggerElement, TooltipTriggerPro
           data-state={context.stateAttribute}
           {...triggerProps}
           ref={composedTriggerRef}
-          onMouseEnter={composeEventHandlers(props.onMouseEnter, context.onOpen)}
+          onMouseOver={composeEventHandlers(props.onMouseOver, context.onOpen)}
```
Comment (jjenzz) [inline packages/react/tooltip/src/Tooltip.tsx:238]: There is an issue with this... If a dialog close button (for example) is positioned on top of a tooltip trigger, when the dialog closes the tooltip will open:

https://user-images.githubusercontent.com/175330/145034878-49fa44d9-3076-4932-9f92-ee51eebac977.mp4

The alternative is to try adding `pointer-events: none` to the content parts but `Popover` has a wrapping div that cannot be styled.

Comment (benoitgrelard) [reply packages/react/tooltip/src/Tooltip.tsx:238]: I'm not sure it's an issue actually. To be honest, I kinda like it that it does that!

**Review by benoitgrelard — APPROVED** [review]

File: packages/react/tooltip/src/Tooltip.tsx (hunk 1 above)
Comment (jjenzz) [reply packages/react/tooltip/src/Tooltip.tsx:238]: Furry muff 🎉
