### PR TITLE
[RovingFocusGroup] Fix Safari issues

### LINKED ISSUE #703: [ToggleGroup] Weird focus behavior in Safari (MacOS, iOS and iPadOS)
## Bug report

EDIT: this applies to Safari on all platforms (iOS, iPadOS, and MacOS).

### Current Behavior

MacOS Safari using mouse input:

https://user-images.githubusercontent.com/11911299/121565598-95f00f00-c9ea-11eb-81ae-011e90734253.mov

iOS iPhone using touch input:
https://user-images.githubusercontent.com/11911299/121562868-e154ee00-c9e7-11eb-9cc6-993c47243bc7.MP4

iPadOS iPad using mouse input:
https://user-images.githubusercontent.com/11911299/121562878-e3b74800-c9e7-11eb-933e-d6988fe93477.MP4

### Expected behavior

Focus should match the selected toggle, or not be called (by default Safari doesn't call focus on buttons from touch and mouse input).

### Reproducible example

Use the demo on the docs page with Safari (MacOS, iOS, iPadOS): https://radix-ui.com/primitives/docs/components/toggle-group

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Toggle Group     |    v0.0.8     |
| React            | n/a     |    v17     |
| Browser          |    MacOS, iOS and iPadOS  Safari   |    v14     |

### PR DESCRIPTION
**Pull request by benoitgrelard**
Fixes #703

### CODE REVIEW

File: packages/react/roving-focus/src/RovingFocusGroup.tsx [hunk 1]
```diff
@@ -136,8 +137,18 @@ const RovingFocusGroupImpl = React.forwardRef((props, forwardedRef) => {
         {...groupProps}
         as={as}
         ref={composedRefs}
+        style={{ outline: 'none', ...props.style }}
+        onMouseDown={composeEventHandlers(props.onMouseDown, () => {
+          isClickFocusRef.current = true;
+        })}
         onFocus={composeEventHandlers(props.onFocus, (event) => {
-          if (event.target === event.currentTarget && !isTabbingBackOut) {
+          // We normally wouldn't need this check, because we already check
```
Comment (benoitgrelard) [inline packages/react/roving-focus/src/RovingFocusGroup.tsx:145]: Let me know how you find the comments.

File: packages/react/roving-focus/src/RovingFocusGroup.tsx [hunk 2]
```diff
@@ -198,6 +211,8 @@ const RovingFocusItem = React.forwardRef((props, forwardedRef) => {
           // We prevent focusing non-focusable items on `mousedown`.
           // Even though the item has tabIndex={-1}, that only means take it out of the tab order.
           if (!focusable) event.preventDefault();
+          // Safari doesn't focus a button when clicked so we run our logic on mousedown also
```
Comment (benoitgrelard) [inline packages/react/roving-focus/src/RovingFocusGroup.tsx:214]: It occurred to me whilst writing this comment (and the other one too) that we do this because of buttons and mention buttons, even though this render a `span` by default. So there's a bit of a disconnect here. It's obviously the neatest place to fix it, but how can we bridge the gap a bit better in terms of explanation?

Comment (jjenzz) [reply packages/react/roving-focus/src/RovingFocusGroup.tsx:214]: Oh yeah... that's a bit poop but can't think of a better way of handling it so 🤷

**Review by jjenzz — APPROVED** [review]

**Review by andy-hook — APPROVED** [review]
