### PR TITLE
[RadioGroup] Prevent radio activation on manual focus

### LINKED ISSUE #938: [RadioGroup] Focusing a radio item causes the radio group value to change as if that item was clicked
First things first: Radix is **wonderful**. Thank you for creating it!

---

### Current Behavior

Programmatically focusing an `Item` in a Radix radio group causes that `Item` to become checked.

### Expected behavior

Programmatically focusing an `Item` should not cause it to become checked.

### Reproducible example

https://codesandbox.io/s/festive-goldstine-sjt3o?file=/App.js

To repro: Click the button and see that the checked `Item` changes (unexpectedly... I'm pretty sure).

### Suggested solution

I'm not sure

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-radio-group     |     0.1.1    |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |     Version 96.0.4664.18 (Official Build) beta (arm64)    |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |    whatever codesandbox is using     |         |
| Operating System |    macOS     |     12.0.1    |

### PR DESCRIPTION
**Pull request by jjenzz**
Fixes #938 

-------------

Easier to review with hidden whitespace changes

-------------

### CODE REVIEW

**Comment by jjenzz** [comment]
@benoitgrelard this is ready for a second look whenever you're free 🙏

File: packages/react/radio-group/src/RadioGroup.tsx [hunk 1]
```diff
@@ -146,7 +165,7 @@ const RadioGroupItem = React.forwardRef<RadioGroupItemElement, RadioGroupItemPro
              * We do this imperatively instead of updating `context.value` because changing via
              * state would not trigger change events (e.g. when in a form).
              */
-            if (context.value !== undefined) ref.current?.click();
+            if (isArrowKeyPressedRef.current) ref.current?.click();
```
[the remark this answers is not in the document]
Comment (benoitgrelard) [reply packages/react/radio-group/src/RadioGroup.tsx:168]: I don't think it's worth abstracting anything yet really. We can always bring that logic in `RovingFocusGroup` later if we need to.

File: packages/react/radio-group/src/RadioGroup.tsx [hunk 2]
```diff
@@ -146,7 +165,7 @@ const RadioGroupItem = React.forwardRef<RadioGroupItemElement, RadioGroupItemPro
              * We do this imperatively instead of updating `context.value` because changing via
              * state would not trigger change events (e.g. when in a form).
              */
```
Comment (benoitgrelard) [inline packages/react/radio-group/src/RadioGroup.tsx:167]: I wonder if we need to fledge this comment to explain why we do the arrow check?

**Review by benoitgrelard — APPROVED** [review]
Pragmatic solution, I like it! 👍

File: packages/react/radio-group/src/RadioGroup.tsx (hunk 2 above)
Comment (jjenzz) [reply packages/react/radio-group/src/RadioGroup.tsx:167]: Does this line cover it? https://github.com/radix-ui/primitives/pull/939/files#diff-39138edb5652b34ca612c34d47986e2e8eb2c97315f178b7fe237b28e0a2aeeaR164

I thought it implied arrow keypress since that's what roving focus does but let me know if you'd prefer something more explicit here.

Comment (benoitgrelard) [reply packages/react/radio-group/src/RadioGroup.tsx:167]: Sorry I can't see where this is pointing to for some reason…

Comment (jjenzz) [reply packages/react/radio-group/src/RadioGroup.tsx:167]: Ah it's because GitHub collapses that line ...
image

Comment (benoitgrelard) [reply packages/react/radio-group/src/RadioGroup.tsx:167]: To be honest the second half of that comment confuses me now 😀
The first half is correct, although I feel like it could be clearer now that we've added the arrow keys check.

Perhaps something like:

```
Our `RovingFocusGroup` will focus item as we navigate with arrow keys.
We need to make that "check" that item when that's the case.
However, programatic focus should not "check" the focused item.
```

Comment (jjenzz) [reply packages/react/radio-group/src/RadioGroup.tsx:167]: The second part of the comment is explaining why we imperatively call `.click()` to check it instead of setting `context.value` to the current items value (declarative). I think we still need that information.

Does this work?

```jsx
Our `RovingFocusGroup` will focus the radio when navigating with arrow keys and 
we need to "check" it in that case. We click it to "check" it (instead of updating 
`context.value`) so that the radio change event fires.
```
