### PR TITLE
[Slider] Fix sticky value with keyboard

### LINKED ISSUE #732: [Slider] Extra keypress required to move thumb
https://user-images.githubusercontent.com/175330/122761147-d164c600-d293-11eb-8ad9-0c3ac7621a9c.mp4

When the thumb reaches the same value as another thumb, I have to press the arrow one extra time than I should need to for it to move.

### PR DESCRIPTION
**Pull request by jjenzz**
Fixes #732

### CODE REVIEW

File: packages/react/slider/src/Slider.tsx [hunk 1]
```diff
@@ -117,7 +117,7 @@ const Slider = React.forwardRef((props, forwardedRef) => {
       const nextValues = getNextSortedValues(prevValues, nextValue, atIndex);
       if (hasMinStepsBetweenValues(nextValues, minStepsBetweenThumbs * step)) {
         valueIndexToChangeRef.current = nextValues.indexOf(nextValue);
-        return nextValues[atIndex] !== prevValues[atIndex] ? nextValues : prevValues;
+        return String(nextValues) === String(prevValues) ? prevValues : nextValues;
```
Comment (benoitgrelard) [inline packages/react/slider/src/Slider.tsx:120]: I understand the change, but I can't wrap my head around why the previous way would create the keyboard bug yet this wouldn't. 🤔

**Review by benoitgrelard — APPROVED** [review]

File: packages/react/slider/src/Slider.tsx (hunk 1 above)
Comment (jjenzz) [reply packages/react/slider/src/Slider.tsx:120]: For anyone else following along, without this change we ended up with something like this:

```
[15,16,20] = atIndex = 0, valueIndexToChange = 0
[16,16,20] = atIndex = 0, valueIndexToChange = 0
[16,17,20] = atIndex = 0, valueIndexToChange = 1
```

That last array would then check `nextValues[0] !== prevValues[0]` (`16 !== 16`) which would be equal and return the `prevValues`.
